#
NativeAudioMac.dylib : NativeAudioMac.m
#	clang -dynamiclib -framework CoreAudio -framework Foundation -framework AudioToolbox NativeAudioMac.m -o NativeAudioMac.dylib
	clang -dynamiclib -arch arm64 -arch x86_64 -framework CoreAudio -framework Foundation -framework AudioToolbox NativeAudioMac.m -o NativeAudioMac.dylib
